language: python
branches:
  only:
  - source
install:
- pip install markdown pelican ghp-import
- git clone https://github.com/getpelican/pelican-plugins
- cd pelican-plugins
- git clone https://github.com/wrobstory/pelican_dynamic.git
- cd ..
script:
- make publish github
env:
  global:
    secure: A8hE1H+16WlKAu5K4ZqqpLv14MBUC9rtQGc6RCIJV2zcHbpvwXQ/6HS6T5tTKd3J/XKzullWi/qM2oQyY+3NcTp08qs+z91wVBBBa4eu20m29BbZ5/1TL8RvVEWv3TWjZ4LdzJCBkkOe1FJgAUEFdP9QXcEANZjc+/nLcOenqDJeDlr7Hp2lInhnkwntfvAdh1cMDzBweETfcZTcmXYQaa89/ori2886qTYr3XlBkHuzn7kBj4VZSlRlPZiihM2cmzQ7UBZBgk2xM2a9oYda16fRsQ3Xto8TscmWUQxNAjbU+of/365il8Pc3z1mOF/zPAt84N90VvAcWUHUZnzSrNgHRPE2cmeAAcVx9RZnlUvNoZc3RzVTZs80NkmSNnFvEsgS77ZF35SwUcems5hB0bTlMxAmAaMinAR2JFXasTj0/h4hzUq1+0Fluypve/ZaBg5H18k9mdAErD99GcGv+JQof4RqFNcfs/70RzzLUjnjE/MFtt1cnwvgHweyNcGatVGHT+s3V2eN+W5vnMEmb3SFlEIbnYtOT5kevaEcvbHnFE1b/AypZty4VK6fmB+qsQbQxDFOInfe2jvsSTkfQnkrSVVk45ygQqq1lUUxCGyyq3WlB42jUK8AXmR0rKc4VRqZ+Xvt1qPym9PHJ6it8FoRoZEy4Dzx+5P/IUCuiWA=
